// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var ReactSelect = require("react-select");
var JsonDecoder$ReactHooksTemplate = require("./JsonDecoder.bs.js");

var url = "https://gist.githubusercontent.com/rusty-key/659db3f4566df459bd59c8a53dc9f71f/raw/4127f9550ef063121c564025f6d27dceeb279623/counties.json";

function decodeCountries(xs) {
  var JsonToCountry = JsonDecoder$ReactHooksTemplate.MakeJsonDecoder(/* module */[]);
  return Curry._1(JsonToCountry[/* parseArray */0], xs);
}

function findInCountries(xs, value) {
  return Belt_Array.getBy(xs, (function (c) {
                return c[/* value */1] === value;
              }));
}

function CountrySelect(Props) {
  var onChange = Props.onChange;
  var value = Props.value;
  var match = React.useState((function () {
          return "";
        }));
  var setError = match[1];
  var match$1 = React.useState((function () {
          return /* array */[];
        }));
  var setCountries = match$1[1];
  var countries = match$1[0];
  React.useEffect((function () {
          fetch(url).then((function (prim) {
                    return prim.json();
                  })).then((function (a) {
                  var match = decodeCountries(a);
                  if (match.tag) {
                    var e = match[0];
                    Curry._1(setError, (function (param) {
                            return e;
                          }));
                  } else {
                    var xs = match[0];
                    Curry._1(setCountries, (function (param) {
                            return xs;
                          }));
                  }
                  return Promise.resolve(a);
                }));
          return (function (param) {
                    return /* () */0;
                  });
        }), /* array */[]);
  return React.createElement("div", undefined, match[0], value !== undefined ? React.createElement(ReactSelect.default, {
                    value: findInCountries(countries, value),
                    onChange: onChange,
                    options: countries
                  }) : null);
}

var make = CountrySelect;

exports.url = url;
exports.decodeCountries = decodeCountries;
exports.findInCountries = findInCountries;
exports.make = make;
/* react Not a pure module */
