// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var CountrySelect$ReactHooksTemplate = require("./CountrySelect.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(CountrySelect$ReactHooksTemplate.make, {
          onChange: (function (prim) {
              console.log(prim);
              return /* () */0;
            }),
          value: "us"
        }), "index");

/*  Not a pure module */
